### ISSUE TITLE
options for distortion polynomials 

### ISSUE THREAD

**Issue by willemrood** [neuromorphicsystems/astrometry#1]
Hi there, 

package works well as intended although I have two suggestions/questions regarding fitting distortion polynomials. We use a wide FoV setup (24mm, 53x74 deg FoV) and we need at least a 6 order polynomial to fit the distortions for accurate wcs2pix conversions. The current solution outputs with a 2nd (?) order SIP correction and only limited options for fitting anything afterwards (stars list != target list). 

- Is it possible to export a list of targets and matched stars such that we can do our own distortion fitting, or
- Is it possible to add a kwarg for setting the tune_up order polynomial? 
btw the link to the tweak2 method of astrometry.net seems to be dead in the documentation. 

Kind regards

**Comment by aMarcireau** [comment]
Hi,

The Astrometry.net C API, which this package uses, does not provide access to the matched catalogue stars (at least to my knowledge). However, I should be able to add support for higher-order SIP corrections.

For reference, the tweak2 method is implemented here: https://github.com/dstndstn/astrometry.net/blob/47849f0443b890c4a875360f881d2e60d1cba630/solver/tweak2.c#L195

Kind regards,
Alex

**Comment by aMarcireau** [comment]
Hi @willemrood,

I published a new version of Astrometry (https://pypi.org/project/astrometry/3.0.0/) with support for more solver options, including the SIP correction order (details here: https://github.com/neuromorphicsystems/astrometry#solutionparameters).

Can you let me know if that works as intended with your data?
